In [1]:
from linares_plot import *
import sys, os
path_tools = 'C:\\Users\\David\\Documents\\GitHub\\encoding\\scripts\\wm_representation\\functions\\IEM\\tools'
sys.path.insert(1, path_tools)
from tiemcourse_interference import *
from scipy import stats
from scipy.stats import norm

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
df = pd.read_excel('C:\\Users\\David\\Desktop\\KI_Desktop\\data_reconstructions\\IEM\\IEM_trainT_decoded_angle.xlsx')
len(df)

89856

In [4]:
def err_deg(a1,ref):
    ### Calculate the error ref-a1 in an efficient way in the circular space
    ### it uses complex numbers!
    ### Input in degrees (0-360)
    a1=np.radians(a1)
    ref=np.radians(ref)
    err = np.angle(np.exp(1j*ref)/np.exp(1j*(a1) ), deg=True) 
    err=round(err, 2)
    return err

In [5]:
error_ = [err_deg(df.iloc[i].decoded_angle, df.iloc[i].target_centered) for i in range(len(df)) ]
distr_distance = [err_deg(df.iloc[i].distractor_centered, df.iloc[i].target_centered) for i in range(len(df)) ]

df['error'] = error_
df['error_abs'] = abs(np.array(error_))
df['distractor_distance'] = distr_distance
df['distractor_distance_abs'] = abs(np.array(distr_distance))

df['sign_dist'] = df.distractor_distance<0
df['sign_dist'] = df['sign_dist'].replace([True, False], ['ccw', 'cw']) #position of the distractor relative to the target

C:\Users\David\Anaconda3\envs\python3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in cdouble_scalars
  import sys


In [6]:
df_beh = pd.read_excel('C:\\Users\\David\\Desktop\\KI_Desktop\\data_reconstructions\\IEM\\IEM_trainT_decoded_angle_related_behaviour.xlsx')

In [7]:
df_beh.head()

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  Dist_NT2  \
0           0     1     0.2    11.8  142  241  321  126.0     214.7      64.0   
1           4     3     0.2    11.8  312   42  232  113.0      29.4     206.6   
2           7     3     0.2    11.8  131  242  339   43.0     230.4     311.9   
3           8     3     0.2    11.8  313   39  243  153.0      22.4     215.4   
4           9     1     0.2    11.8  137  227  302  118.5     200.5      69.0   

   ...  dist_alone  T_close  dist_close  subject  session  run  session_run  \
0  ...          64      142       126.0     d001       10    1         10_1   
1  ...         113       42        29.4     d001       10    1         10_1   
2  ...          43      242       230.4     d001       10    1         10_1   
3  ...         153       39        22.4     d001       10    1         10_1   
4  ...          69      137       118.5     d001       10    1         10_1   

   new_index  brain_region  condition  
0          0        visual      1_0.2  
1          1        visual      1_0.2  
2          2        visual      1_0.2  
3          3        visual      1_0.2  
4          4        visual      1_0.2  

[5 rows x 47 columns]

In [8]:
len(df_beh)

5964

In [13]:
df_beh.loc[(df_beh['subject']=='l001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') ].new_index.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], dtype=int64)

In [18]:
df_example = df_beh.loc[(df_beh['subject']=='l001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') ]

In [32]:
df_example

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
5046           0     1     0.2    11.8  142  241  321  126.0     214.7   
5047           4     3     0.2    11.8  312   42  232  113.0      29.4   
5048           7     3     0.2    11.8  131  242  339   43.0     230.4   
5049           8     3     0.2    11.8  313   39  243  153.0      22.4   
5050           9     1     0.2    11.8  137  227  302  118.5     200.5   
...          ...   ...     ...     ...  ...  ...  ...    ...       ...   
5121           2     3     0.2    11.8  334  228   69  142.0     214.9   
5122           6     1     0.2    11.8  299  117   37  316.5     145.4   
5123           8     3     0.2    11.8  334  123   62  233.0     110.0   
5124          18     3     0.2    11.8  333  157   53  218.0     138.8   
5125          25     1     0.2    11.8  290  216   39  304.6     244.0   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
5046      64.0  ...          64      142       126.0     l001        1    1   
5047     206.6  ...         113       42        29.4     l001        1    1   
5048     311.9  ...          43      242       230.4     l001        1    1   
5049     215.4  ...         153       39        22.4     l001        1    1   
5050      69.0  ...          69      137       118.5     l001        1    1   
...        ...  ...         ...      ...         ...      ...      ...  ...   
5121      40.7  ...         142      228       214.9     l001        4    4   
5122     210.0  ...         210      299       316.5     l001        4    4   
5123      39.1  ...         233      123       110.0     l001        4    4   
5124      32.0  ...         218      157       138.8     l001        4    4   
5125     129.0  ...         129      290       304.6     l001        4    4   

      session_run  new_index  brain_region  condition  
5046          1_1          0        visual      1_0.2  
5047          1_1          1        visual      1_0.2  
5048          1_1          2        visual      1_0.2  
5049          1_1          3        visual      1_0.2  
5050          1_1          4        visual      1_0.2  
...           ...        ...           ...        ...  
5121          4_4         75        visual      1_0.2  
5122          4_4         76        visual      1_0.2  
5123          4_4         77        visual      1_0.2  
5124          4_4         78        visual      1_0.2  
5125          4_4         79        visual      1_0.2  

[80 rows x 47 columns]

In [19]:
df_example.columns

Index(['Unnamed: 0', 'type', 'delay1', 'delay2', 'T', 'NT1', 'NT2', 'Dist',
       'Dist_NT1', 'Dist_NT2', 'distance_T_dist', 'cue', 'order', 'orient',
       'horiz_vertical', 'A_R', 'A_err', 'Abs_angle_error',
       'Error_interference', 'A_DC', 'A_DC_dist', 'Q_DC', 'A_DF', 'A_DF_dist',
       'Q_DF', 'A_DVF', 'Q_DVF', 'A_DVF_dist', 'Q_DVF_dist',
       'presentation_att_cue_time', 'presentation_target_time',
       'presentation_dist_time', 'presentation_probe_time', 'R_T',
       'trial_time', 'disp_time', 'T_alone', 'dist_alone', 'T_close',
       'dist_close', 'subject', 'session', 'run', 'session_run', 'new_index',
       'brain_region', 'condition'],
      dtype='object')

In [35]:
sum(df_example['T'].values == df_example['T_alone'].values)

41

In [ ]:
df_beh.loc[(df_beh['subject']=='l001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') ].new_index.unique()

In [37]:
df.head()

Unnamed: 0  decoded_angle  target_centered label_target  corresp_isolated  \
0           0     190.770087              180            T             False   
1           1     165.634003              180          NT1             False   
2           2     178.169130              180          NT2              True   
3           3     170.110002              180            T             False   
4           4     212.278508              180          NT1             False   

   distractor_centered  corresp_isolated_distractor label_distractor  \
0                164.0                        False             Dist   
1                153.7                        False         Dist_NT1   
2                283.0                         True         Dist_NT2   
3                161.5                        False             Dist   
4                153.5                        False         Dist_NT1   

   new_index   TR subject brain_region condition  error  error_abs  \
0          0  0.0    d001       visual     1_0.2 -10.77      10.77   
1          0  0.0    d001       visual     1_0.2  14.37      14.37   
2          0  0.0    d001       visual     1_0.2   1.83       1.83   
3          4  0.0    d001       visual     1_0.2   9.89       9.89   
4          4  0.0    d001       visual     1_0.2 -32.28      32.28   

   distractor_distance  distractor_distance_abs sign_dist  
0                 16.0                     16.0        cw  
1                 26.3                     26.3        cw  
2               -103.0                    103.0       ccw  
3                 18.5                     18.5        cw  
4                 26.5                     26.5        cw

In [64]:
df.loc[(df['subject']=='r001') & (df['condition']=='2_7') & (df['brain_region']=='visual') ]

Unnamed: 0  decoded_angle  target_centered label_target  \
49296           0     199.468705              180            T   
49297           1     161.891897              180          NT1   
49298           2     209.152766              180          NT2   
49299           3     180.564141              180            T   
49300           4     185.556095              180          NT1   
...           ...            ...              ...          ...   
50491        1195     188.638891              180          NT1   
50492        1196            NaN              180          NT2   
50493        1197     198.634002              180            T   
50494        1198            NaN              180          NT1   
50495        1199     170.595551              180          NT2   

       corresp_isolated  distractor_centered  corresp_isolated_distractor  \
49296              True                297.0                         True   
49297             False                161.2                        False   
49298             False                150.5                        False   
49299              True                346.0                         True   
49300             False                164.6                        False   
...                 ...                  ...                          ...   
50491             False                197.9                        False   
50492             False                205.4                        False   
50493             False                192.4                        False   
50494             False                206.9                        False   
50495              True                 87.0                         True   

      label_distractor  new_index      TR subject brain_region condition  \
49296             Dist          1   0.000    r001       visual       2_7   
49297         Dist_NT1          1   0.000    r001       visual       2_7   
49298         Dist_NT2          1   0.000    r001       visual       2_7   
49299             Dist          3   0.000    r001       visual       2_7   
49300         Dist_NT1          3   0.000    r001       visual       2_7   
...                ...        ...     ...     ...          ...       ...   
50491         Dist_NT1         16  35.025    r001       visual       2_7   
50492         Dist_NT2         16  35.025    r001       visual       2_7   
50493             Dist         26  35.025    r001       visual       2_7   
50494         Dist_NT1         26  35.025    r001       visual       2_7   
50495         Dist_NT2         26  35.025    r001       visual       2_7   

       error  error_abs  distractor_distance  distractor_distance_abs  \
49296 -19.47      19.47               -117.0                    117.0   
49297  18.11      18.11                 18.8                     18.8   
49298 -29.15      29.15                 29.5                     29.5   
49299  -0.56       0.56               -166.0                    166.0   
49300  -5.56       5.56                 15.4                     15.4   
...      ...        ...                  ...                      ...   
50491  -8.64       8.64                -17.9                     17.9   
50492    NaN        NaN                -25.4                     25.4   
50493 -18.63      18.63                -12.4                     12.4   
50494    NaN        NaN                -26.9                     26.9   
50495   9.40       9.40                 93.0                     93.0   

      sign_dist  
49296       ccw  
49297        cw  
49298        cw  
49299       ccw  
49300        cw  
...         ...  
50491       ccw  
50492       ccw  
50493       ccw  
50494       ccw  
50495        cw  

[1200 rows x 18 columns]

In [65]:
df.loc[(df['subject']=='n001') & (df['condition']=='2_7') & (df['brain_region']=='visual') ]

Unnamed: 0  decoded_angle  target_centered label_target  \
19008           0     183.644174              180            T   
19009           1     171.542720              180          NT1   
19010           2     200.863046              180          NT2   
19011           3     178.094140              180            T   
19012           4     150.759727              180          NT1   
...           ...            ...              ...          ...   
20203        1195     184.360627              180          NT1   
20204        1196     186.362784              180          NT2   
20205        1197     208.995104              180            T   
20206        1198     181.640085              180          NT1   
20207        1199     163.167884              180          NT2   

       corresp_isolated  distractor_centered  corresp_isolated_distractor  \
19008              True                297.0                         True   
19009             False                161.2                        False   
19010             False                150.5                        False   
19011              True                346.0                         True   
19012             False                164.6                        False   
...                 ...                  ...                          ...   
20203             False                197.9                        False   
20204             False                205.4                        False   
20205             False                192.4                        False   
20206             False                206.9                        False   
20207              True                 87.0                         True   

      label_distractor  new_index      TR subject brain_region condition  \
19008             Dist          1   0.000    n001       visual       2_7   
19009         Dist_NT1          1   0.000    n001       visual       2_7   
19010         Dist_NT2          1   0.000    n001       visual       2_7   
19011             Dist          3   0.000    n001       visual       2_7   
19012         Dist_NT1          3   0.000    n001       visual       2_7   
...                ...        ...     ...     ...          ...       ...   
20203         Dist_NT1         16  35.025    n001       visual       2_7   
20204         Dist_NT2         16  35.025    n001       visual       2_7   
20205             Dist         26  35.025    n001       visual       2_7   
20206         Dist_NT1         26  35.025    n001       visual       2_7   
20207         Dist_NT2         26  35.025    n001       visual       2_7   

       error  error_abs  distractor_distance  distractor_distance_abs  \
19008  -3.64       3.64               -117.0                    117.0   
19009   8.46       8.46                 18.8                     18.8   
19010 -20.86      20.86                 29.5                     29.5   
19011   1.91       1.91               -166.0                    166.0   
19012  29.24      29.24                 15.4                     15.4   
...      ...        ...                  ...                      ...   
20203  -4.36       4.36                -17.9                     17.9   
20204  -6.36       6.36                -25.4                     25.4   
20205 -29.00      29.00                -12.4                     12.4   
20206  -1.64       1.64                -26.9                     26.9   
20207  16.83      16.83                 93.0                     93.0   

      sign_dist  
19008       ccw  
19009        cw  
19010        cw  
19011       ccw  
19012        cw  
...         ...  
20203       ccw  
20204       ccw  
20205       ccw  
20206       ccw  
20207        cw  

[1200 rows x 18 columns]

In [66]:
df.loc[(df['subject']=='l001') & (df['condition']=='1_0.2')  & (df['label_target']=='T') 
       & (df['brain_region']=='visual') & (df['TR']==0.000)  ]

Unnamed: 0  decoded_angle  target_centered label_target  \
75168           0     177.258102              180            T   
75171           3     164.948893              180            T   
75174           6     150.677208              180            T   
75177           9     194.419003              180            T   
75180          12     180.749558              180            T   
75183          15     185.266250              180            T   
75186          18     175.374077              180            T   
75189          21     183.028689              180            T   
75192          24     163.511397              180            T   
75195          27     158.817890              180            T   
75198          30     176.755928              180            T   
75201          33     206.753890              180            T   
75204          36     158.713780              180            T   
75207          39     184.395594              180            T   
75210          42     167.531597              180            T   
75213          45     172.757677              180            T   
75216          48     189.173845              180            T   
75219          51     159.213558              180            T   
75222          54     173.410512              180            T   
75225          57     182.155558              180            T   
75228          60     194.889624              180            T   
75231          63     171.633768              180            T   
75234          66     155.821829              180            T   
75237          69     168.796436              180            T   
75240          72     171.407980              180            T   
75243          75     173.955928              180            T   

       corresp_isolated  distractor_centered  corresp_isolated_distractor  \
75168             False                164.0                        False   
75171             False                161.5                        False   
75174              True                349.0                         True   
75177              True                246.0                         True   
75180             False                194.2                        False   
75183             False                199.0                        False   
75186             False                198.8                        False   
75189              True                357.0                         True   
75192              True                 75.0                         True   
75195              True                341.0                         True   
75198              True                 92.0                         True   
75201             False                194.1                        False   
75204              True                341.0                         True   
75207             False                191.8                        False   
75210              True                  5.0                         True   
75213              True                265.0                         True   
75216             False                167.8                        False   
75219             False                164.0                        False   
75222              True                 20.0                         True   
75225             False                162.9                        False   
75228              True                277.0                         True   
75231              True                 92.0                         True   
75234              True                294.0                         True   
75237              True                116.0                         True   
75240              True                 70.0                         True   
75243              True                 97.0                         True   

      label_distractor  new_index   TR subject brain_region condition  error  \
75168             Dist          0  0.0    l001       visual     

In [67]:
df_beh.loc[(df_beh['subject']=='l001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') ]

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
5046           0     1     0.2    11.8  142  241  321  126.0     214.7   
5047           4     3     0.2    11.8  312   42  232  113.0      29.4   
5048           7     3     0.2    11.8  131  242  339   43.0     230.4   
5049           8     3     0.2    11.8  313   39  243  153.0      22.4   
5050           9     1     0.2    11.8  137  227  302  118.5     200.5   
...          ...   ...     ...     ...  ...  ...  ...    ...       ...   
5121           2     3     0.2    11.8  334  228   69  142.0     214.9   
5122           6     1     0.2    11.8  299  117   37  316.5     145.4   
5123           8     3     0.2    11.8  334  123   62  233.0     110.0   
5124          18     3     0.2    11.8  333  157   53  218.0     138.8   
5125          25     1     0.2    11.8  290  216   39  304.6     244.0   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
5046      64.0  ...          64      142       126.0     l001        1    1   
5047     206.6  ...         113       42        29.4     l001        1    1   
5048     311.9  ...          43      242       230.4     l001        1    1   
5049     215.4  ...         153       39        22.4     l001        1    1   
5050      69.0  ...          69      137       118.5     l001        1    1   
...        ...  ...         ...      ...         ...      ...      ...  ...   
5121      40.7  ...         142      228       214.9     l001        4    4   
5122     210.0  ...         210      299       316.5     l001        4    4   
5123      39.1  ...         233      123       110.0     l001        4    4   
5124      32.0  ...         218      157       138.8     l001        4    4   
5125     129.0  ...         129      290       304.6     l001        4    4   

      session_run  new_index  brain_region  condition  
5046          1_1          0        visual      1_0.2  
5047          1_1          1        visual      1_0.2  
5048          1_1          2        visual      1_0.2  
5049          1_1          3        visual      1_0.2  
5050          1_1          4        visual      1_0.2  
...           ...        ...           ...        ...  
5121          4_4         75        visual      1_0.2  
5122          4_4         76        visual      1_0.2  
5123          4_4         77        visual      1_0.2  
5124          4_4         78        visual      1_0.2  
5125          4_4         79        visual      1_0.2  

[80 rows x 47 columns]

In [68]:
df_example  = df_beh.loc[(df_beh['subject']=='l001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') ]
df_example[df_example['T'].values == df_example['T_alone'].values]

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
5047           4     3     0.2    11.8  312   42  232  113.0      29.4   
5048           7     3     0.2    11.8  131  242  339   43.0     230.4   
5049           8     3     0.2    11.8  313   39  243  153.0      22.4   
5052          14     3     0.2    11.8  309   49  248  134.0      34.0   
5053          18     3     0.2    11.8  301   52  233  110.0      35.8   
5054          19     3     0.2    11.8   45  323  200  111.0     335.0   
5057           8     3     0.2    11.8  306  146   42  242.0     156.3   
5061           5     3     0.2    11.8  309  204  135   63.0     216.8   
5062           6     3     0.2    11.8  140   49  331  225.0      33.3   
5064          16     3     0.2    11.8  206  145  315   23.0     127.3   
5065          17     3     0.2    11.8   50  150  247  305.0     138.0   
5066          23     3     0.2    11.8  135  324   25  232.0     338.9   
5067          24     3     0.2    11.8   64  117  202  314.0     131.6   
5068          25     3     0.2    11.8  149  217  312   66.0     227.6   
5070           4     3     0.2    11.8  312   42  232  113.0      29.4   
5071           7     3     0.2    11.8  131  242  339   43.0     230.4   
5072           8     3     0.2    11.8  313   39  243  153.0      22.4   
5075          14     3     0.2    11.8  309   49  248  134.0      34.0   
5076          18     3     0.2    11.8  301   52  233  110.0      35.8   
5077          19     3     0.2    11.8   45  323  200  111.0     335.0   
5081           8     3     0.2    11.8  300  225   41  150.0     242.5   
5082          10     3     0.2    11.8  246  335   55  137.0     318.2   
5083          16     3     0.2    11.8  337  224   34  145.0     235.5   
5085           6     3     0.2    11.8   33  143  323  238.0     128.0   
5088           6     3     0.2    11.8  133  317  200   57.0     329.3   
5091          17     3     0.2    11.8   32  238  332  153.0     220.5   
5092          20     3     0.2    11.8  337  207  128   26.0     218.6   
5095           5     3     0.2    11.8  120   29  295  239.0      39.5   
5096          12     3     0.2    11.8  310  209   29  146.0     228.5   
5101           6     3     0.2    11.8  134  206   28  295.0     225.1   
5103          13     3     0.2    11.8  110   55  207  298.0      68.9   
5104          14     3     0.2    11.8   49  238  141  299.0     225.9   
5109           2     3     0.2    11.8  222  322  110   67.0     335.2   
5110           3     3     0.2    11.8   57  308  224  158.0     292.4   
5114          11     3     0.2    11.8  337  230   56  155.0     219.3   
5117          18     3     0.2    11.8  224  317   63  143.0     303.2   
5118          21     3     0.2    11.8  126   40  337  201.0      26.0   
5119          22     3     0.2    11.8  304   54  116  214.0      67.3   
5121           2     3     0.2    11.8  334  228   69  142.0     214.9   
5123           8     3     0.2    11.8  334  123   62  233.0     110.0   
5124          18     3     0.2    11.8  333  157   53  218.0     138.8   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
5047     206.6  ...         113       42        29.4     l001        1    1   
5048     311.9  ...          43      242       230.4     l001        1    1   
5049     215.4  ...         153       39        22.4     l001        1    1   
5052     220.4  ...         134       49        34.0     l001        1    1   
5053     203.5  ...         110       52        35.8     l001        1    1   
5054     225.9  ...         111      323       335.0     l001        1    1   
5057      66.8  ...         242      146       156.3     l001        1    2   
5061     156.1  ...          63      204       216.8     l001        1    3   
5062     308.6  ...         225       49        33.3     l001        1    3   
5064     291.1  ...          23      145       127.3     l001        1    3   
5065     217.4  ...         

# Que pasa?

In [117]:
df_reconst = df.loc[(df['subject']=='n001') & (df['condition']=='1_0.2')  & (df['label_target']=='T') 
       & (df['brain_region']=='visual') & (df['TR']==0.000)  ]

In [118]:
df_reconst

Unnamed: 0  decoded_angle  target_centered label_target  \
15120           0     204.808354              180            T   
15123           3     199.139792              180            T   
15126           6     185.528899              180            T   
15129           9     187.225924              180            T   
15132          12     148.945889              180            T   
15135          15     189.189164              180            T   
15138          18     211.385712              180            T   
15141          21     174.250369              180            T   
15144          24     184.090092              180            T   
15147          27     177.095055              180            T   
15150          30     149.438277              180            T   
15153          33     215.807267              180            T   
15156          36     166.323761              180            T   
15159          39     179.085368              180            T   
15162          42     173.116754              180            T   
15165          45     170.260242              180            T   
15168          48     209.450754              180            T   
15171          51     156.909681              180            T   
15174          54     184.843740              180            T   
15177          57     167.936639              180            T   
15180          60     184.964691              180            T   
15183          63     175.885754              180            T   
15186          66     202.289140              180            T   
15189          69     164.260604              180            T   
15192          72     171.655988              180            T   
15195          75     137.318949              180            T   
15198          78     156.554859              180            T   

       corresp_isolated  distractor_centered  corresp_isolated_distractor  \
15120             False                164.0                        False   
15123             False                161.5                        False   
15126              True                349.0                         True   
15129              True                246.0                         True   
15132             False                194.2                        False   
15135             False                199.0                        False   
15138             False                198.8                        False   
15141              True                357.0                         True   
15144              True                 75.0                         True   
15147              True                 30.0                         True   
15150              True                 71.0                         True   
15153             False                194.1                        False   
15156              True                341.0                         True   
15159             False                191.8                        False   
15162              True                  5.0                         True   
15165              True                265.0                         True   
15168             False                167.8                        False   
15171             False                166.8                        False   
15174              True                 70.0                         True   
15177              True                348.0                         True   
15180              True                 20.0                         True   
15183             False                162.9                        False   
15186              True                277.0                         True   
15189              True                 92.0                         True   
15192              True                 97.0                         True   
15195              True                294.0                         True   
15198              True                116.0                         True   

 

In [119]:
len(df_reconst)

27

In [ ]:
#### En los reconstructed, cuando voy a los "target" para un determinado subject, tengo 26 trials

In [120]:
df_behaviour = df_beh.loc[(df_beh['subject']=='n001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') ]

In [121]:
df_behaviour.head()

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
1035           0     1     0.2    11.8  142  241  321  126.0     214.7   
1036           4     3     0.2    11.8  312   42  232  113.0      29.4   
1037           7     3     0.2    11.8  131  242  339   43.0     230.4   
1038           8     3     0.2    11.8  313   39  243  153.0      22.4   
1039           9     1     0.2    11.8  137  227  302  118.5     200.5   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
1035      64.0  ...          64      142       126.0     n001        1    1   
1036     206.6  ...         113       42        29.4     n001        1    1   
1037     311.9  ...          43      242       230.4     n001        1    1   
1038     215.4  ...         153       39        22.4     n001        1    1   
1039      69.0  ...          69      137       118.5     n001        1    1   

      session_run  new_index  brain_region  condition  
1035          1_1          0        visual      1_0.2  
1036          1_1          1        visual      1_0.2  
1037          1_1          2        visual      1_0.2  
1038          1_1          3        visual      1_0.2  
1039          1_1          4        visual      1_0.2  

[5 rows x 47 columns]

In [122]:
len(df_behaviour)

96

In [131]:
df_behaviour.columns

Index(['Unnamed: 0', 'type', 'delay1', 'delay2', 'T', 'NT1', 'NT2', 'Dist',
       'Dist_NT1', 'Dist_NT2', 'distance_T_dist', 'cue', 'order', 'orient',
       'horiz_vertical', 'A_R', 'A_err', 'Abs_angle_error',
       'Error_interference', 'A_DC', 'A_DC_dist', 'Q_DC', 'A_DF', 'A_DF_dist',
       'Q_DF', 'A_DVF', 'Q_DVF', 'A_DVF_dist', 'Q_DVF_dist',
       'presentation_att_cue_time', 'presentation_target_time',
       'presentation_dist_time', 'presentation_probe_time', 'R_T',
       'trial_time', 'disp_time', 'T_alone', 'dist_alone', 'T_close',
       'dist_close', 'subject', 'session', 'run', 'session_run', 'new_index',
       'brain_region', 'condition'],
      dtype='object')

In [ ]:
actual_T = 'T'
actual_dist = 'Dist'
actual_response = 'A_R'
actual_Error = 'A_err'

In [123]:
## Veo que tengo 80 trials

In [124]:
### Solo estoy cogiendo una sesion????? Diría que sí! la primera, aunque hay algunos trials que bailan...

In [125]:
df_sess4 = df_behaviour.loc[df_behaviour['session']==1]
df_sess4.head()

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
1035           0     1     0.2    11.8  142  241  321  126.0     214.7   
1036           4     3     0.2    11.8  312   42  232  113.0      29.4   
1037           7     3     0.2    11.8  131  242  339   43.0     230.4   
1038           8     3     0.2    11.8  313   39  243  153.0      22.4   
1039           9     1     0.2    11.8  137  227  302  118.5     200.5   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
1035      64.0  ...          64      142       126.0     n001        1    1   
1036     206.6  ...         113       42        29.4     n001        1    1   
1037     311.9  ...          43      242       230.4     n001        1    1   
1038     215.4  ...         153       39        22.4     n001        1    1   
1039      69.0  ...          69      137       118.5     n001        1    1   

      session_run  new_index  brain_region  condition  
1035          1_1          0        visual      1_0.2  
1036          1_1          1        visual      1_0.2  
1037          1_1          2        visual      1_0.2  
1038          1_1          3        visual      1_0.2  
1039          1_1          4        visual      1_0.2  

[5 rows x 47 columns]

In [126]:
len(df_sess4)

35

In [127]:
### Podría ser.... Ver si encaja con la rotación de estos trials...

In [128]:
distance_to_ref =  df_sess4['T'].values- 180

        #
dist_180_ = df_sess4['Dist'].values - distance_to_ref
dist_180 = []
for n_dist in dist_180_:
    if n_dist<0:
        n_ = n_dist+360
        dist_180.append(n_)
    elif n_dist>360:
        n_ = n_dist-360
        dist_180.append(n_)
    else:
        dist_180.append(n_dist)
##
dist_180 = np.array(dist_180)

In [129]:
dist_180.sort()
dist_180

array([  5. ,  19. ,  20. ,  25. ,  30. ,  68. ,  70. ,  71. ,  75. ,
        92. ,  97. , 116. , 161.5, 162.9, 164. , 166.8, 166.9, 167.8,
       169.3, 190.5, 191.8, 194.1, 194.2, 198.8, 199. , 246. , 258. ,
       265. , 277. , 277. , 294. , 341. , 348. , 349. , 357. ])

In [130]:
sort__ = df_reconst.distractor_centered.values
sort__.sort()
sort__

array([  5. ,  20. ,  30. ,  70. ,  71. ,  75. ,  92. ,  97. , 116. ,
       161.5, 162.9, 164. , 166.8, 167.8, 191.8, 194.1, 194.2, 198.8,
       199. , 246. , 265. , 277. , 294. , 341. , 348. , 349. , 357. ])

In [96]:
df_behaviour.session_run.unique()

array(['1_1', '1_2', '1_3', '2_1', '2_2', '2_3', '3_1', '3_2', '3_4',
       '4_1', '4_2', '4_3', '4_4'], dtype=object)

In [98]:
for sess_run in df_behaviour.session_run.unique():
    df_behaviour.loc[df_behaviour['session_run']==sess_run].index.values 

In [103]:
df_behaviour.loc[df_behaviour['session_run']==sess_run].index.values

array([5120, 5121, 5122, 5123, 5124, 5125], dtype=int64)

In [105]:
training_indexes = []
testing_indexes =  []
for sess_run in df_behaviour.session_run.unique():
    wanted = df_behaviour.loc[df_behaviour['session_run']==sess_run].index.values 
    testing_indexes.append( wanted )
    #
    ## I do not trust the del  lines of other files, maybe this del inside a function in paralel is not removing the indexes, also you avoid going to lists to comeback
    all_indexes = df_behaviour.index.values
    other_indexes = all_indexes[~np.array([all_indexes[i] in wanted for i in range(len(all_indexes))])]  #take the ones that are not in wanted
    training_indexes.append( other_indexes )

In [107]:
testing_indexes

[array([5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056],
       dtype=int64),
 array([5057, 5058], dtype=int64),
 array([5059, 5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068],
       dtype=int64),
 array([5069, 5070, 5071, 5072, 5073, 5074, 5075, 5076, 5077, 5078, 5079],
       dtype=int64),
 array([5080, 5081, 5082, 5083], dtype=int64),
 array([5084, 5085], dtype=int64),
 array([5086, 5087, 5088, 5089, 5090, 5091, 5092], dtype=int64),
 array([5093, 5094, 5095, 5096], dtype=int64),
 array([5097, 5098, 5099], dtype=int64),
 array([5100, 5101, 5102, 5103, 5104, 5105, 5106, 5107, 5108], dtype=int64),
 array([5109, 5110, 5111, 5112], dtype=int64),
 array([5113, 5114, 5115, 5116, 5117, 5118, 5119], dtype=int64),
 array([5120, 5121, 5122, 5123, 5124, 5125], dtype=int64)]

In [115]:
testing_indexes[0]

array([5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056],
      dtype=int64)

In [113]:
df_behaviour

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
5046           0     1     0.2    11.8  142  241  321  126.0     214.7   
5047           4     3     0.2    11.8  312   42  232  113.0      29.4   
5048           7     3     0.2    11.8  131  242  339   43.0     230.4   
5049           8     3     0.2    11.8  313   39  243  153.0      22.4   
5050           9     1     0.2    11.8  137  227  302  118.5     200.5   
...          ...   ...     ...     ...  ...  ...  ...    ...       ...   
5121           2     3     0.2    11.8  334  228   69  142.0     214.9   
5122           6     1     0.2    11.8  299  117   37  316.5     145.4   
5123           8     3     0.2    11.8  334  123   62  233.0     110.0   
5124          18     3     0.2    11.8  333  157   53  218.0     138.8   
5125          25     1     0.2    11.8  290  216   39  304.6     244.0   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
5046      64.0  ...          64      142       126.0     l001        1    1   
5047     206.6  ...         113       42        29.4     l001        1    1   
5048     311.9  ...          43      242       230.4     l001        1    1   
5049     215.4  ...         153       39        22.4     l001        1    1   
5050      69.0  ...          69      137       118.5     l001        1    1   
...        ...  ...         ...      ...         ...      ...      ...  ...   
5121      40.7  ...         142      228       214.9     l001        4    4   
5122     210.0  ...         210      299       316.5     l001        4    4   
5123      39.1  ...         233      123       110.0     l001        4    4   
5124      32.0  ...         218      157       138.8     l001        4    4   
5125     129.0  ...         129      290       304.6     l001        4    4   

      session_run  new_index  brain_region  condition  
5046          1_1          0        visual      1_0.2  
5047          1_1          1        visual      1_0.2  
5048          1_1          2        visual      1_0.2  
5049          1_1          3        visual      1_0.2  
5050          1_1          4        visual      1_0.2  
...           ...        ...           ...        ...  
5121          4_4         75        visual      1_0.2  
5122          4_4         76        visual      1_0.2  
5123          4_4         77        visual      1_0.2  
5124          4_4         78        visual      1_0.2  
5125          4_4         79        visual      1_0.2  

[80 rows x 47 columns]

In [76]:
df_behaviour

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
5046           0     1     0.2    11.8  142  241  321  126.0     214.7   
5047           4     3     0.2    11.8  312   42  232  113.0      29.4   
5048           7     3     0.2    11.8  131  242  339   43.0     230.4   
5049           8     3     0.2    11.8  313   39  243  153.0      22.4   
5050           9     1     0.2    11.8  137  227  302  118.5     200.5   
...          ...   ...     ...     ...  ...  ...  ...    ...       ...   
5121           2     3     0.2    11.8  334  228   69  142.0     214.9   
5122           6     1     0.2    11.8  299  117   37  316.5     145.4   
5123           8     3     0.2    11.8  334  123   62  233.0     110.0   
5124          18     3     0.2    11.8  333  157   53  218.0     138.8   
5125          25     1     0.2    11.8  290  216   39  304.6     244.0   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
5046      64.0  ...          64      142       126.0     l001        1    1   
5047     206.6  ...         113       42        29.4     l001        1    1   
5048     311.9  ...          43      242       230.4     l001        1    1   
5049     215.4  ...         153       39        22.4     l001        1    1   
5050      69.0  ...          69      137       118.5     l001        1    1   
...        ...  ...         ...      ...         ...      ...      ...  ...   
5121      40.7  ...         142      228       214.9     l001        4    4   
5122     210.0  ...         210      299       316.5     l001        4    4   
5123      39.1  ...         233      123       110.0     l001        4    4   
5124      32.0  ...         218      157       138.8     l001        4    4   
5125     129.0  ...         129      290       304.6     l001        4    4   

      session_run  new_index  brain_region  condition  
5046          1_1          0        visual      1_0.2  
5047          1_1          1        visual      1_0.2  
5048          1_1          2        visual      1_0.2  
5049          1_1          3        visual      1_0.2  
5050          1_1          4        visual      1_0.2  
...           ...        ...           ...        ...  
5121          4_4         75        visual      1_0.2  
5122          4_4         76        visual      1_0.2  
5123          4_4         77        visual      1_0.2  
5124          4_4         78        visual      1_0.2  
5125          4_4         79        visual      1_0.2  

[80 rows x 47 columns]

In [ ]:
df_example[df_example['T'].values == df_example['T_alone'].values]

In [11]:
df_beh.loc[(df_beh['subject']=='l001') & (df_beh['condition']=='1_0.2') & (df_beh['brain_region']=='visual') & (df_beh['new_index']==1) ]

Unnamed: 0  type  delay1  delay2    T  NT1  NT2   Dist  Dist_NT1  \
5047           4     3     0.2    11.8  312   42  232  113.0      29.4   

      Dist_NT2  ...  dist_alone  T_close  dist_close  subject  session  run  \
5047     206.6  ...         113       42        29.4     l001        1    1   

      session_run  new_index  brain_region  condition  
5047          1_1          1        visual      1_0.2  

[1 rows x 47 columns]

In [12]:
df.loc[(df['subject']=='n001') & (df['condition']=='1_0.2') & (df['brain_region']=='visual') &  (df['new_index']==1)  &  (df['TR']==) ]

SyntaxError: invalid syntax (<ipython-input-12-48ae19705413>, line 1)

In [42]:
T=312
NT1=42
NT2=232

Dist=113.0
Dist_NT1=29.4
Dist_NT2=206.6


dif_t = T-180
T_1 = T - dif_t
Dist_1 = Dist - dif_t

if Dist_1<0:
    Dist_1=360 + Dist_1
elif Dist_1>360:
    Dist_1 = Dist_1-360

print(T_1, Dist_1)

dif_t = NT1-180
T_2 = NT1 - dif_t
Dist_2 = Dist_NT1 - dif_t

if Dist_2<0:
    Dist_2=360 + Dist_2
elif Dist_2>360:
    Dist_2 = Dist_2-360

print(T_2, Dist_2)

dif_t = NT2-180
T_3 = NT2 - dif_t
Dist_3 = Dist_NT2 - dif_t

if Dist_3<0:
    Dist_3=360 + Dist_3
elif Dist_3>360:
    Dist_3 = Dist_3-360

print(T_3, Dist_3)
    
    

180 341.0
180 167.4
180 154.6


In [38]:
360-(113-132)

379

In [18]:
df.loc[(df['subject']=='n001') & (df['condition']=='1_0.2') & (df['brain_region']=='visual') & (df['new_index']==3)  ]

Unnamed: 0  decoded_angle  target_centered label_target  \
15180          60     184.964691              180            T   
15181          61     138.026423              180          NT1   
15182          62     159.501153              180          NT2   
15261         141     174.926297              180            T   
15262         142     155.457397              180          NT1   
15263         143     181.817055              180          NT2   
15342         222     158.614798              180            T   
15343         223     173.118246              180          NT1   
15344         224     167.760673              180          NT2   
15423         303     183.327886              180            T   
15424         304     190.012226              180          NT1   
15425         305     163.679235              180          NT2   
15504         384     174.170943              180            T   
15505         385     203.623377              180          NT1   
15506         386     171.934196              180          NT2   
15585         465     167.194688              180            T   
15586         466     206.866413              180          NT1   
15587         467     169.961075              180          NT2   
15666         546     176.713457              180            T   
15667         547     210.776380              180          NT1   
15668         548            NaN              180          NT2   
15747         627     185.513515              180            T   
15748         628     212.648170              180          NT1   
15749         629     169.472622              180          NT2   
15828         708     197.552050              180            T   
15829         709     156.543666              180          NT1   
15830         710     173.924167              180          NT2   
15909         789     188.969547              180            T   
15910         790     164.959325              180          NT1   
15911         791     209.431578              180          NT2   
15990         870     183.619173              180            T   
15991         871     154.555338              180          NT1   
15992         872     202.818447              180          NT2   
16071         951     193.977816              180            T   
16072         952     153.269068              180          NT1   
16073         953     164.574282              180          NT2   
16152        1032     172.672189              180            T   
16153        1033     199.177756              180          NT1   
16154        1034     161.653508              180          NT2   
16233        1113     191.728794              180            T   
16234        1114     206.027989              180          NT1   
16235        1115     157.385768              180          NT2   
16314        1194     186.239366              180            T   
16315        1195     200.331283              180          NT1   
16316        1196     155.845075              180          NT2   
16395        1275     183.076021              180            T   
16396        1276     179.151749              180          NT1   
16397        1277     148.227065              180          NT2   

       corresp_isolated  distractor_centered  corresp_isolated_distractor  \
15180              True                 20.0                         True   
15181             False                163.4                        False   
15182             False                152.4                        False   
15261              True                 20.0                         True   
15262             False                163.4                        False   
15263             False                152.4                        False   
15342              True                 20.0                         True   
15343             False                163.4                        False   
15344             False                152.4                        False   
15

In [16]:
1296/3/27

16.0